
insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (92, '第三方代煎药', '三煎', '第三方代煎药处方', 0, '3,4', null, null, 0, 1, '4717719600', '1,2,3,4,5,6,7,8', 4, '10', null, null, null);

insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (91, '外送处方', '外送', '外送处方笺', 0, '1,2', null, null, 0, 1, '4717719600', '1,2,3,4,5,6', 3, '3', null, null, null);

insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (96, 'ty', null, null, 0, '1', null, null, 0, 1, '4717719600', null, 1, null, null, null, null);

insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (95, 'ty测试', 'ty', 'ty', 0, '4', null, null, 1, 1, '4717719600', null, 4, null, null, null, null);

insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (2, '普通处方', '普通', '普通处方笺', 0, '1,2', null, null, 1, 1, '4717719600', '1,2,3,4,5,6', 1, '2', null, null, null);

insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (3, '急诊处方', '急诊', '急诊处方笺', 0, '1,2', null, null, 0, 1, '4717719600', '1,2,3,4,5,6', 1, '3', null, null, null);

insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (4, '麻醉处方', '特病', '麻醉药品处方笺', 0, '1,2', null, null, 0, 1, '4717719600', '1,2,3,4,7', 1, '4', 'MZ', null, 'M0');

insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (5, '中药饮片处方', '中饮', '中药饮片处方笺', 0, '3,4', null, null, 1, 1, '4717719600', null, 1, '5', null, null, null);

insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (6, '免煎中药饮片处方', '免煎', '免煎中药饮片处方笺', 0, '3,4', null, null, 0, 1, '4717719600', null, 1, '6', null, null, null);

insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (7, '毒性药品', '毒品', '毒性药品处方', 0, '1,2', null, null, 0, 1, '4717719600', '2,3,4,5,6,7', 1, '7', 'MZ', null, 'D0');

insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (8, '儿科处方', '儿', '儿科处方笺', 0, '1,2', null, null, 0, 1, '4717719600', '1,2,3,4,5,6', 1, '8', null, null, null);

insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (9, '精一', '精神', '精神药品处方笺', 0, '1,2', null, null, 0, 1, '4717719600', '1,3,4,5,6,7', 1, '9', 'MZ', null, 'J1');

insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (10, '精二', '精二', '精神处方笺', 0, '1,2', null, null, 0, 1, '4717719600', '1,2,5,6,7', 1, '10', null, null, 'J2');

insert into OIS_DIC_PRE_CATEGORY (ID, NAME, SHORT_NAME, TITLE, HINT, PRES_TYPE, ASSOS_REG_DEPT, ASSOS_NATURE, IS_DEFAULT, STATE, BRANCH_CODE, MED_LIMIT, TYPE, CODE, TAG, INDEPENDENT_SEQ, SIGN_GRADE)
values (1, '医保处方', '医保', '基本医疗保险处方笺', 0, '1,2,3,4', null, null, 0, 1, '4717719600', '6,5,4,3,2,1', 1, '1', null, null, null);
